export const countries = [
    { code : "AU", name : "Austrailia" },
    { code : "AT", name : "Austria" },
    { code : "BE", name : "Belgium" },
    { code : "BR", name : "Brazil" },
    { code : "BG", name : "Bulgaria" },
    { code : "CA", name : "Canada" },
    { code : "HR", name : "Croatia" },
    { code : "CY", name : "Cyprus" },
    { code : "CZ", name : "Czech Republic" },
    { code : "DK", name : "Denmark" },
    { code : "EE", name : "Estonia" },
    { code : "FI", name : "Finland" },
    { code : "FR", name : "France" },
    { code : "DE", name : "Germany" },
    { code : "GR", name : "Greece" },
    { code : "HK", name : "Hong Kong" },
    { code : "HU", name : "Hungary" },
    { code : "IN", name : "India" },
    { code : "IE", name : "Ireland" },
    { code : "IT", name : "Italy" },
    { code : "JP", name : "Japan" },
    { code : "LV", name : "Latvia" },
    { code : "LT", name : "Lithuania" },
    { code : "LU", name : "Luxembourg" },
    { code : "MT", name : "Malta" },
    { code : "MX", name : "Mexico" },
    { code : "NL", name : "Netherlands" },
    { code : "NZ", name : "New Zealand" },
    { code : "NO", name : "Norway" },
    { code : "PL", name : "Poland" },
    { code : "PT", name : "Portugal" },
    { code : "RO", name : "Romania" },
    { code : "SG", name : "Singapore" },
    { code : "SK", name : "Slovakia" },
    { code : "SI", name : "Slovenia" },
    { code : "ES", name : "Spain" },
    { code : "SE", name : "Sweden" },
    { code : "CH", name : "Switzerland" },
    { code : "TH", name : "Thailand" },
    { code : "GB", name : "United Kingdom" },
    { code : "US", name : "United States" },
]

export const categories = [
    { value : "clothing", label : "Clothing & Apparel" },
    { value : "electronics", label : "Electronics & Gadgets" },
    { value : "grocery", label : "Grocery & Supermarket" },
    { value : "restaurant", label : "Restaurants & Cafe's" },
    { value : "beauty", label : "Beauty & Personal Care" },
    { value : "furniture", label : "Furniture & Home Decor" },
    { value : "automotive", label : "Automotive & Accessories" },
    { value : "books", label : "Books & Stationary" },
    { value : "toys", label : "Toys & Games" },
    { value : "sports", label : "Sports & Fitness" },
    { value : "hardware", label : "Hardware & Tools" },
    { value : "pet", label : "Pet Supplies & Services" },
    { value : "medical", label : "Medical & Pharmacy" },
    { value : "jewlery", label : "Jewelery" },
    { value : "watch", label : "Watches" },
    { value : "florist", label : "Florists & Gift Shops" },
    { value : "baby", label : "Baby & Kids Store" },
    { value : "art", label : "Art & Craft Supplies" },
    { value : "music", label : "Music Instruments & Stores" },
    { value : "technology", label : "Software & Technology Services" },
    { value : "garden", label : "Garden & Outdoor Equipment" },
    { value : "bakery", label : "Bakery & Confectionary" },
    { value : "optical", label : "Optical & Eyewear" },
    { value : "mobile", label : "Mobile Phone & Accessories" },
    { value : "real_estate", label : "Real Estate & Property Services" },
    { value : "fitness", label : "Fitness & Wellness Center" },
    { value : "entertainment", label : "Entertainment & Gaming" },
    { value : "other", label : "Other" },
]